/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lyh.rpc;

import com.lyh.rpc.client.ProxyFactory;
import com.lyh.rpc.server.RPCHandler;
import com.lyh.rpc.server.RPCServer;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

public class RPCTests {
    @Test
    void basic() throws IOException {
        RPCServer.start();

        // register to server
        RPCHandler handler = RPCHandler.getInstance();
        handler.register(this.ITestImpl);

        // get proxy
        ITest test = ProxyFactory.getProxy(ITest.class);

        // rpc
        final String info = "information";
        final String expected = SUCCESS_FLAG + info;
        String actual = test.test(info);

        assertEquals(expected, actual);
    }

    public interface ITest{
        String test(String info);
    }

    private final String SUCCESS_FLAG = "success:";

    private ITest ITestImpl = new ITest() {
        @Override
        public String test(String info) {
            return SUCCESS_FLAG + info;
        }
    };
}
